import type { Metadata } from "next";
import { SidebarProvider } from "@/components/navigation/sidebar/Sidebar";
import { AppSidebar } from "@/components/navigation/sidebar/AppSidebar";
import AppHeader from "@/components/navigation/header/AppHeader";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        storageKey="theme"
        enableSystem
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <AppHeader>{children}</AppHeader>
          </main>
        </SidebarProvider>
      </ThemeProvider>
    </section>
  );
}
