import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/navigation/sidebar/Sidebar";
import { AppSidebar } from "@/components/navigation/sidebar/AppSidebar";
import AppHeader from "@/components/navigation/header/AppHeader";
import { ThemeProvider } from "@/components/theme-provider";

const montserratSans = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserratSans.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          storageKey="theme"
          enableSystem
        >
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full">
              <AppHeader>{children}</AppHeader>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
